// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Victor.Models;

#nullable disable

namespace Victor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240502141054_Migrations")]
    partial class Migrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Victor.Models.Folha", b =>
                {
                    b.Property<string>("FolhaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ImpostoFGTS")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImpostoINSS")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImpostoIRRF")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SalarioBruto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalarioLiquido")
                        .HasColumnType("TEXT");

                    b.Property<int>("Valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("FolhaId");

                    b.ToTable("Folhas");
                });

            modelBuilder.Entity("Victor.Models.Funcionario", b =>
                {
                    b.Property<string>("FuncionarioId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CPF")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("FuncionarioId");

                    b.ToTable("Funcionarios");
                });
#pragma warning restore 612, 618
        }
    }
}
